export { default as Navigation } from "./Navigation";
export { default as Footer } from "./Footer";
export { default as Register } from "./Register";
export { default as Login } from "./Login";
export { default as Logout } from "./Logout";
export { default as Home } from "./Home";
export { default as About } from "./About";
export { default as Wordbase } from "./Wordbase";
export { default as Anagram } from "./Anagram";